module.exports = [{
        "idDrink": "11000",
        "strDrink": "Mojito",
        "strTags": "IBA,ContemporaryClassic,Alcoholic,USA",
        "strCategory": "Cocktail",
        "strIBA": "Contemporary Classics",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Highball glass",
        "strInstructions": "Muddle mint leaves with sugar and lime juice. Add a splash of soda water and fill the glass with cracked ice. Pour the rum and top with soda water. Garnish and serve with straw.",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/rxtqps1478251029.jpg",
        "strIngredients": ["Light rum", "Lime", "Sugar", "Mint", "Soda water"],
        "strMeasure1": "2-3 oz ",
        "strMeasure2": "Juice of 1 ",
        "strMeasure3": "2 tsp ",
        "strMeasure4": "2-4 ",
        "dateModified": "2016-11-04 09:17:09"
    }, {
        "idDrink": "11007",
        "strDrink": "Margarita",
        "strTags": "IBA,ContemporaryClassic",
        "strCategory": "Ordinary Drink",
        "strIBA": "Contemporary Classics",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Cocktail glass",
        "strInstructions": "Rub the rim of the glass with the lime slice to make the salt stick to it. Take care to moisten only the outer rim and sprinkle the salt on it. The salt should present to the lips of the imbiber and never mix into the cocktail. Shake the other ingredients with ice, then carefully pour into the glass.",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/wpxpvu1439905379.jpg",
        "strIngredients": ["Tequila", "Triple sec", "Lime juice", "Salt"],
        "strMeasure1": "1 1/2 oz ",
        "strMeasure2": "1/2 oz ",
        "strMeasure3": "1 oz ",
        "dateModified": "2015-08-18 14:42:59"
    }, {
        "idDrink": "12322",
        "strDrink": "Strawberry Margarita",
        "strCategory": "Ordinary Drink",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Cocktail glass",
        "strInstructions": "Rub rim of cocktail glass with lemon juice and dip rim in salt. Shake schnapps, tequila, triple sec, lemon juice, and strawberries with ice, strain into the salt-rimmed glass, and serve.",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/tqyrpw1439905311.jpg",
        "strIngredients": ["Strawberry schnapps", "Tequila", "Triple sec", "Lemon juice", "Strawberries", "Salt"],
        "strMeasure1": "1/2 oz ",
        "strMeasure2": "1 oz ",
        "strMeasure3": "1/2 oz ",
        "strMeasure4": "1 oz ",
        "strMeasure5": "1 oz ",
        "dateModified": "2015-08-18 14:41:51"
    }, {
        "idDrink": "11006",
        "strDrink": "Daiquiri",
        "strTags": "IBA,Classic,Beach",
        "strCategory": "Ordinary Drink",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Cocktail glass",
        "strInstructions": "Pour all ingredients into shaker with ice cubes. Shake well. Strain in chilled cocktail glass.",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/usuuur1439906797.jpg",
        "strIngredients": ["Light rum", "Lime", "Powdered sugar"],
        "strMeasure1": "1 1/2 oz ",
        "strMeasure2": "Juice of 1/2 ",
        "strMeasure3": "1 tsp ",
        "dateModified": "2015-08-18 15:06:37"
    }, {
        "idDrink": "12754",
        "strDrink": "Sex on the Beach",
        "strTags": "IBA,ContemporaryClassic",
        "strCategory": "Ordinary Drink",
        "strIBA": "Contemporary Classics",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Highball glass",
        "strInstructions": "Build all ingredients in a highball glass filled with ice. Garnish with orange slice.",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/lijtw51551455287.jpg",
        "strIngredients": ["Vodka", "Peach schnapps", "Cranberry juice", "Grapefruit juice"],
        "dateModified": "2016-07-21 10:12:45"
    }, {
        "idDrink": "17207",
        "strDrink": "Pina Colada",
        "strTags": "IBA,ContemporaryClassic",
        "strCategory": "Ordinary Drink",
        "strIBA": "Contemporary Classics",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Collins glass",
        "strInstructions": "Mix with crushed ice in blender until smooth. Pour into chilled glass, garnish and serve.",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/cpf4j51504371346.jpg",
        "strIngredients": ["Light rum", "Coconut milk", "Pineapple"],
        "strMeasure1": "3 oz ",
        "strMeasure2": "3 tblsp ",
        "strMeasure3": "3 tblsp ",
        "dateModified": "2017-09-02 17:55:46"
    }, {
        "idDrink": "11600",
        "strDrink": "Kamikaze",
        "strTags": "IBA,NewEra",
        "strCategory": "Ordinary Drink",
        "strIBA": "New Era Drinks",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Cocktail glass",
        "strInstructions": "Shake all ingredients together with ice. Strain into glass, garnish and serve.",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/xa58bb1504373204.jpg",
        "strIngredients": ["Vodka", "Triple sec", "Lime juice"],
        "dateModified": "2017-09-02 18:26:44"
    }, {
        "idDrink": "17196",
        "strDrink": "Cosmopolitan",
        "strTags": "IBA,ContemporaryClassic",
        "strCategory": "Cocktail",
        "strIBA": "Contemporary Classics",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Cocktail glass",
        "strInstructions": "Add all ingredients into cocktail shaker filled with ice. Shake well and double strain into large cocktail glass. Garnish with lime wheel.",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/kpsajh1504368362.jpg",
        "strIngredients": ["Absolut Citron", "Lime juice", "Cointreau", "Cranberry juice"],
        "strMeasure1": "1 1/4 oz ",
        "strMeasure2": "1/4 oz ",
        "strMeasure3": "1/4 oz ",
        "strMeasure4": "1/4 cup ",
        "dateModified": "2017-09-02 17:06:02"
    }, {
        "idDrink": "13621",
        "strDrink": "Tequila Sunrise",
        "strTags": "IBA,ContemporaryClassic",
        "strCategory": "Cocktail",
        "strIBA": "Contemporary Classics",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Highball glass",
        "strInstructions": "Pour the tequila and orange juice into glass over ice. Add the grenadine, which will sink to the bottom. Stir gently to create the sunrise effect. Garnish and serve.",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/quqyqp1480879103.jpg",
        "strIngredients": ["Tequila", "Orange juice", "Grenadine"],
        "strMeasure1": "2 measures ",
        "dateModified": "2016-12-04 19:18:23"
    }, {
        "idDrink": "11728",
        "strDrink": "Martini",
        "strCategory": "Cocktail",
        "strIBA": "Unforgettables",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Cocktail glass",
        "strInstructions": "Straight: Pour all ingredients into mixing glass with ice cubes. Stir well. Strain in chilled martini cocktail glass. Squeeze oil from lemon peel onto the drink, or garnish with olive.",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/71t8581504353095.jpg",
        "strIngredients": ["Gin", "Dry Vermouth", "Olive"],
        "strMeasure1": "1 2/3 oz ",
        "strMeasure2": "1/3 oz ",
        "strMeasure3": "1 ",
        "dateModified": "2017-09-02 12:51:35"
    }, {
        "idDrink": "14167",
        "strDrink": "Vodka Martini",
        "strCategory": "Ordinary Drink",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Cocktail glass",
        "strInstructions": "Shake the vodka and vermouth together with a number of ice cubes, strain into a cocktail glass, add the olive and serve.",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/qyxrqw1439906528.jpg",
        "strIngredients": ["Vodka", "Dry Vermouth", "Olive"],
        "strMeasure1": "1 1/2 oz ",
        "strMeasure2": "3/4 oz ",
        "strMeasure3": "1 ",
        "dateModified": "2015-08-18 15:02:08"
    }, {
        "idDrink": "17204",
        "strDrink": "Long Island Iced Tea",
        "strTags": "IBA,ContemporaryClassic",
        "strCategory": "Ordinary Drink",
        "strIBA": "Contemporary Classics",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Highball glass",
        "strInstructions": "Mix all contents in a highball glass and sitr gently. Add dash of Coca-Cola for the coloring and garnish with lemon or lime twist.",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/wx7hsg1504370510.jpg",
        "strIngredients": ["Vodka", "Tequila", "Light rum", "Gin", "Coca-Cola", "Lemon peel"],
        "strMeasure1": "1/2 oz ",
        "strMeasure2": "1/2 oz ",
        "strMeasure3": "1/2 oz ",
        "strMeasure4": "1/2 oz ",
        "strMeasure5": "1 dash ",
        "strMeasure6": "Twist of ",
        "dateModified": "2017-09-02 17:41:50"
    }, {
        "idDrink": "11102",
        "strDrink": "Black Russian",
        "strTags": "IBA,ContemporaryClassic",
        "strCategory": "Ordinary Drink",
        "strIBA": "Contemporary Classics",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Old-fashioned glass",
        "strInstructions": "Pour the ingredients into an old fashioned glass filled with ice cubes. Stir gently.",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/2k5gbb1504367689.jpg",
        "strIngredients": ["Coffee liqueur", "Vodka"],
        "strMeasure1": "3/4 oz ",
        "strMeasure2": "1 1/2 oz ",
        "dateModified": "2017-09-02 16:54:49"
    }, {
        "idDrink": "12528",
        "strDrink": "White Russian",
        "strCategory": "Ordinary Drink",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Old-fashioned glass",
        "strInstructions": "Pour vodka and coffee liqueur over ice cubes in an old-fashioned glass. Fill with light cream and serve.",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/vsrupw1472405732.jpg",
        "strIngredients": ["Vodka", "Coffee liqueur", "Light cream"],
        "strMeasure1": "2 oz ",
        "strMeasure2": "1 oz ",
        "dateModified": "2016-08-28 18:35:32"
    }, {
        "idDrink": "12107",
        "strDrink": "Salty Dog",
        "strCategory": "Ordinary Drink",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Highball glass",
        "strInstructions": "Pour all ingredients over ice cubes in a highball glass. Stir well and serve. (Vodka may be substituted for gin, if preferred.)",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/4vfge01504890216.jpg",
        "strIngredients": ["Grapefruit juice", "Gin", "Salt"],
        "strMeasure1": "5 oz ",
        "strMeasure2": "1 1/2 oz ",
        "strMeasure3": "1/4 tsp ",
        "dateModified": "2017-09-08 18:03:36"
    }, {
        "idDrink": "15853",
        "strDrink": "B-52",
        "strTags": "IBA,NewEra",
        "strCategory": "Shot",
        "strIBA": "New Era Drinks",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Shot glass",
        "strInstructions": "Layer ingredients into a shot glass. Serve with a stirrer.",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/5a3vg61504372070.jpg",
        "strIngredients": ["Bailey's irish cream", "Grand Marnier", "Coffee liqueur"],
        "strMeasure1": "1/3 ",
        "strMeasure2": "1/3 ",
        "strMeasure3": "1/4 ",
        "dateModified": "2017-09-02 18:07:51"
    }, {
        "idDrink": "11288",
        "strDrink": "Cuba Libre",
        "strTags": "IBA,ContemporaryClassic",
        "strCategory": "Ordinary Drink",
        "strIBA": "Contemporary Classics",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Highball glass",
        "strInstructions": "Build all ingredients in a Collins glass filled with ice. Garnish with lime wedge.",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/uuxsrr1473201663.jpg",
        "strIngredients": ["Light rum", "Lime", "Coca-Cola"],
        "strMeasure1": "2 oz ",
        "strMeasure2": "Juice of 1/2 ",
        "dateModified": "2016-09-06 23:41:03"
    }, {
        "idDrink": "11113",
        "strDrink": "Bloody Mary",
        "strTags": "IBA,ContemporaryClassic",
        "strCategory": "Ordinary Drink",
        "strIBA": "Contemporary Classics",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Old-fashioned glass",
        "strInstructions": "Stirring gently, pour all ingredients into highball glass. Garnish.",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/uyquuu1439906954.jpg",
        "strIngredients": ["Vodka", "Tomato juice", "Lemon juice", "Worcestershire sauce", "Tabasco sauce", "Lime"],
        "strMeasure1": "1 1/2 oz ",
        "strMeasure2": "3 oz ",
        "strMeasure3": "1 dash ",
        "strMeasure4": "1/2 tsp ",
        "strMeasure5": "2-3 drops ",
        "strMeasure6": "1 wedge ",
        "dateModified": "2015-08-18 15:09:14"
    }, {
        "idDrink": "11202",
        "strDrink": "Caipirinha",
        "strTags": "ContemporaryClassic,IBA",
        "strCategory": "Ordinary Drink",
        "strIBA": "Contemporary Classics",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Old-fashioned glass",
        "strInstructions": "Place lime and sugar into old fashioned glass and muddle (mash the two ingredients together using a muddler or a wooden spoon). Fill the glass with ice and add the Cachaça.",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/xyrppt1469090521.jpg",
        "strIngredients": ["Sugar", "Lime", "Cachaca"],
        "strMeasure1": "2 tsp",
        "strMeasure2": "1 ",
        "strMeasure3": "2 1/2 oz ",
        "dateModified": "2016-07-21 09:42:01"
    }, {
        "idDrink": "11403",
        "strDrink": "Gin And Tonic",
        "strCategory": "Ordinary Drink",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Highball glass",
        "strInstructions": "Pour the gin and the tonic water into a highball glass almost filled with ice cubes. Stir well. Garnish with the lime wedge.",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/wtyxvx1472405831.jpg",
        "strIngredients": ["Gin", "Tonic water", "Lime"],
        "strMeasure1": "2 oz ",
        "strMeasure2": "5 oz ",
        "strMeasure3": "1 ",
        "dateModified": "2016-08-28 18:37:11"
    }, {
        "idDrink": "11001",
        "strDrink": "Old Fashioned",
        "strTags": "IBA,Classic",
        "strCategory": "Cocktail",
        "strIBA": "Unforgettables",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Old-fashioned glass",
        "strInstructions": "Place sugar cube in old fashioned glass and saturate with bitters, add a dash of plain water. Muddle until dissolved. Fill the glass with ice cubes and add whiskey.         Garnish with orange twist, and a cocktail cherry.",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/vrwquq1478252802.jpg",
        "strIngredients": ["Bourbon", "Angostura bitters", "Sugar", "Water"],
        "strMeasure1": "4.5 cL",
        "strMeasure2": "2 dashes",
        "strMeasure3": "1 cube",
        "strMeasure4": "dash",
        "dateModified": "2016-11-04 09:46:42"
    }, {
        "idDrink": "17218",
        "strDrink": "Vesper",
        "strTags": "IBA,NewEra",
        "strCategory": "Cocktail",
        "strIBA": "New Era Drinks",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Cocktail glass",
        "strInstructions": "Shake over ice until well chilled, then strain into a deep goblet and garnish with a thin slice of lemon peel.",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/mtdxpa1504374514.jpg",
        "strIngredients": ["Gin", "Vodka", "Lillet Blanc"],
        "strMeasure1": "6 cl",
        "strMeasure2": "1.5 cl",
        "strMeasure3": "0.75 cl",
        "dateModified": "2017-09-02 18:48:34"
    }, {
        "idDrink": "11008",
        "strDrink": "Manhattan",
        "strTags": "IBA,Classic",
        "strCategory": "Cocktail",
        "strIBA": "Unforgettables",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Cocktail glass",
        "strInstructions": "Stirred over ice, strained into a chilled glass, garnished, and served up.",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/ec2jtz1504350429.jpg",
        "strIngredients": ["Sweet Vermouth", "Bourbon", "Angostura bitters", "Ice", "Maraschino cherry", "Orange peel"],
        "strMeasure1": "3/4 oz ",
        "strMeasure2": "2 1/2 oz Blended ",
        "strMeasure3": "dash ",
        "strMeasure4": "2 or 3 ",
        "strMeasure5": "1 ",
        "strMeasure6": "1 twist of ",
        "dateModified": "2017-09-02 12:07:09"
    }, {
        "idDrink": "11009",
        "strDrink": "Moscow Mule",
        "strTags": "IBA,ContemporaryClassic",
        "strCategory": "Punch / Party Drink",
        "strIBA": "Contemporary Classics",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Copper Mug",
        "strInstructions": "Combine vodka and ginger beer in a highball glass filled with ice. Add lime juice. Stir gently. Garnish.",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/3pylqc1504370988.jpg",
        "strIngredients": ["Vodka", "Lime juice", "Ginger ale"],
        "strMeasure1": "2 oz ",
        "strMeasure2": "2 oz ",
        "strMeasure3": "8 oz ",
        "dateModified": "2017-09-02 17:49:48"
    }, {
        "idDrink": "17195",
        "strDrink": "Bellini",
        "strTags": "ContemporaryClassic,IBA",
        "strCategory": "Ordinary Drink",
        "strIBA": "Contemporary Classics",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Champagne Flute",
        "strInstructions": "Pour peach purée into chilled flute, add sparkling wine. Stir gently.",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/eaag491504367543.jpg",
        "strIngredients": ["Champagne", "Peach schnapps"],
        "strMeasure1": "6 oz ",
        "strMeasure2": "1 oz ",
        "dateModified": "2017-09-02 16:52:23"
    }, {
        "idDrink": "15224",
        "strDrink": "Malibu Twister",
        "strCategory": "Cocktail",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Highball glass",
        "strInstructions": "Add rum & trister then, add cranberry jucie,stir",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/2dwae41504885321.jpg",
        "strIngredients": ["Malibu rum", "Tropicana", "Cranberry juice"],
        "strMeasure1": "2 parts ",
        "strMeasure2": "2 parts ",
        "strMeasure3": "1 part ",
        "dateModified": "2017-09-08 16:42:01"
    },
    {
        "idDrink": "12916",
        "strDrink": "Egg Nog",
        "strCategory": "Punch / Party Drink",
        "strAlcoholic": "Optional alcohol",
        "strGlass": "Collins Glass",
        "strInstructions": "Whip egg substitute and sugar together, combine with the two kinds of milk, vanilla, and rum. Mix well. Chill over night. Sprinkle with nutmeg. Makes 6 servings.",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/qxuppv1468875308.jpg",
        "strIngredients": ["Egg", "Sugar", "Condensed milk", "Milk", "Vanilla extract", "Rum", "Nutmeg"],
        "strMeasure1": "1/2 cup ",
        "strMeasure2": "3 tblsp ",
        "strMeasure3": "13 oz skimmed ",
        "strMeasure4": "3/4 cup skimmed ",
        "strMeasure5": "1 tsp ",
        "strMeasure6": "1 tsp ",
        "dateModified": "2016-07-18 21:55:08"
    },
    {
        "idDrink": "11004",
        "strDrink": "Whiskey Sour",
        "strTags": "IBA,Classic,Alcoholic",
        "strCategory": "Ordinary Drink",
        "strIBA": "Unforgettables",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Old-fashioned glass",
        "strInstructions": "Shake with ice. Strain into chilled glass, garnish and serve. If served 'On the rocks', strain ingredients into old-fashioned glass filled with ice.",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/o56h041504352725.jpg",
        "strIngredients": ["Blended whiskey", "Lemon", "Powdered sugar", "Maraschino cherry", "Lemon"],
        "strMeasure1": "2 oz ",
        "strMeasure2": "Juice of 1/2 ",
        "strMeasure3": "1/2 tsp ",
        "strMeasure4": "1 ",
        "strMeasure5": "1/2 slice ",
        "dateModified": "2017-09-02 12:45:25"
    }



];